inventory/60-generic
=> inventory: add phpmyadmin group

inventory/50-infrastruture, inventory/60-generic
=> inventory: add dragonfly groups

inventory/50-infrastruture
=> inventory: add missing children

inventory/60-generic
=> inventory: add hddtemp + smartd groups

inventory/50-monitoring
=> inventory: zabbix-agent -> zabbix_agent

inventory/50-infrastruture
=> inventory: add adminer group

inventory/50-infrastruture
=> inventory: add keycloak group

environments/manager/run.sh
=> Add missing git prefix

environments/manager/images.yml
=> docker_postgres -> docker_registry

inventory/50-monitoring
=> inventory: add openstack_health_monitor group

inventory/50-kolla
=> inventory: add bifrost group

README.md
=> REAMDE: cleanup

.github/workflows/pr-labeler.yml, .github/yamllint.yml
=> github: fix pr-labeler job

README.md
=> README: improve title

environments/manager/playbook-bootstrap.yml
=> Replace osism.commons

environments/manager/playbook-bootstrap.yml
=> Add missing roles to the manager bootstrap

inventory/51-kolla
=> Deploy fluentd on all nodes

environments/manager/ansible.cfg
=> manager: remove roles_path

environments/manager/images.yml
=> Remove aptly & installer images

environments/manager/images.yml
=> Add docker registry default values

environments/manager/playbook-bootstrap.yml
=> manager: use osism.commons.timezone

environments/manager/playbook-bootstrap.yml
=> manager: remove role ANXS.utilities

environments/manager/requirements.yml
=> manager: cleanup ansible requirements

environments/manager/images.yml
=> manager: fix registry variables

environments/manager/images.yml
=> Use docker_registry_cephclient + docker_registry_openstackclient

environments/manager/images.yml
=> manager: add awxclient image

environments/manager/playbook-operator.yml
=> Replace deprecated parameter

environments/manager/images.yml
=> manager: use ara 1.5.4

environments/manager/requirements.yml
=> manager: remove ANXS.apt from requirements

gilt.yml
=> Add requirements.txt to gilt configuration

.yamllint.yml
=> yamllint: ignore release directory

.github/workflows/check-shell-syntax.yml, environments/manager/run.sh
=> github: add 'Check shell syntax' workflow

inventory/50-ceph
=> Install the cephclient on the ceph control nodes

inventory/50-kolla
=> inventory: deploy kolla grafana & influxdb on the control nodes

inventory/50-kolla
=> inventory: move haproxy on the control nodes

inventory/51-kolla
=> inventory: place designate bind9 service on the network nodes

inventory/51-kolla
=> inventory: place additional octavia servies on the network nodes

inventory/50-ceph
=> inventory: fix ceph groups

inventory/50-ceph
=> inventory: deploy the cephclient on the manager by default

environments/manager/run.sh
=> manager: always use venv

environments/manager/playbook-reboot.yml
=> manager: use reboot module

inventory/51-kolla
=> inventory: add ironic-ipxe group

inventory/50-kolla, inventory/51-kolla
=> inventory: cleanup kolla groups

environments/manager/images.yml
=> manager: update images

environments/manager/images.yml
=> manager: use awxclient 19.0.0

inventory/50-infrastruture
=> inventory: add minikube group

inventory/50-infrastruture
=> inventory: add kubectl group

environments/manager/images.yml
=> manager: use awx_version

environments/manager/images.yml
=> Set default openstack + ceph versions

environments/manager/images.yml
=> manager: set default awx_version & manager_version

inventory/50-kolla, inventory/51-kolla
=> inventory: add senlin groups

inventory/50-infrastruture
=> inventory: remove pulp

inventory/60-generic
=> inventory: add kompose group

inventory/50-infrastruture
=> inventory: add rundeck group

inventory/50-kolla
=> inventory: add kafka group

inventory/50-kolla
=> inventory: add zookeeper group

inventory/50-kolla
=> inventory: deploy influxdb on the monitoring node

inventory/50-kolla, inventory/51-kolla
=> inventory: add storm groups

inventory/50-kolla, inventory/51-kolla
=> inventory: add trove groups

src/templates/images.yml.j2
=> Sync src/templates/images.yml.j2 with environment/manager/images.yml

environments/manager/images.yml, src/templates/images.yml.j2
=> Add osism/inventory-reconciler image

inventory/60-generic
=> inventory: add heimdall group

environments/manager/playbook-manager.yml
=> manager: restart the manager service

inventory/50-infrastruture
=> inventory: add jenkins group

inventory/50-kolla, inventory/51-kolla
=> inventory: re-add cloudkitty groups

inventory/51-kolla
=> inventory: add octavia-driver-agent group

environments/manager/images.yml, src/templates/images.yml.j2
The AWX integration is not complete. To avoid confusion,
the configuration is removed for the moment
=> Remove awx arguments for the moment

environments/manager/images.yml
=> manager: add client versions

environments/manager/images.yml, src/templates/images.yml.j2
=> Use openstack wallaby

src/templates/images.yml.j2
=> Add client versions to the template file

README.md
=> README: add inventory directory

environments/manager/images.yml, src/templates/images.yml.j2
=> Use pacific as ceph default version

environments/manager/playbook-docker.yml
=> manager: enforce a docker service restart

inventory/50-monitoring
=> inventory: remove zabbix groups

.github/workflows/update-images.yml
=> github: use bot@osism.tech

environments/manager/images.yml, src/templates/images.yml.j2
=> Add awx images

environments/manager/images.yml, src/templates/images.yml.j2
=> Use our own netbox image

environments/manager/images.yml, src/templates/images.yml.j2
=> Add scheduler image

environments/manager/images.yml, src/templates/images.yml.j2
=> Add vault image

environments/manager/images.yml, src/templates/images.yml.j2
=> Fix template

environments/manager/requirements.txt
=> manager: add netaddr to the requirements.txt

environments/manager/images.yml, src/templates/images.yml.j2
=> Add docker_registry_netbox

inventory/50-kolla, inventory/51-kolla
=> inventory: re-add zun groups

inventory/50-infrastruture
=> inventory: add traefik

environments/manager/images.yml, src/templates/images.yml.j2
=> manager: add traefik image

environments/manager/run.sh
=> manager: include infra env for traefik & netbox

inventory/60-generic
=> inventory: add journald group

inventory/50-infrastruture, inventory/60-generic
=> inventory: add atlantis + clamav groups

.github/workflows/check-python-syntax.yml, .github/workflows/check-shell-syntax.yml, .github/workflows/check-yaml-syntax.yml, .github/workflows/test-gilt.yml
=> github: run branch builds on main only

inventory/50-infrastruture
=> inventory: add dnsdist

environments/manager/run.sh
Signed-off-by: Uwe Grawert <grawert@b1-systems.de>
=> Make the Python binary configurable used for venv

inventory/50-infrastruture
=> inventory: add cgit group

environments/manager/images.yml, src/templates/images.yml.j2
=> Remove awx

inventory/51-kolla
Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>
=> Add prometheus-libvirt-exporter group

.github/workflows/test-gilt.yml
=> github: fix syntax issue in test-gilt workflow

environments/manager/images.yml
=> manager: add missing osism-netbox image

inventory/50-infrastruture
assign manager the role tang
Signed-off-by: Mathias Fechner <fechner@osism.tech>
=> add tang server

inventory/50-infrastruture
Close #265
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
=> Wireguard: Add role to infrastructure

inventory/50-infrastruture, inventory/60-generic
Closes of #268
Signed-off-by: Ramona Rautenberg <rautenberg@osism.tech>
=> Sort the entries in the inventory files

inventory/50-infrastruture
partly osism/issues#217
Signed-off-by: Tim Beermann <beermann@osism.tech>
=> add squid group

inventory/50-kolla, inventory/51-kolla, src/check-kolla-inventory.py
Also adds a script to show missing groups in the future
Closes osism/cfg-generics#283
=> Add missing kolla inventory groups

environments/manager/images.yml
=> manager: use yoga as new openstack default version

environments/manager/images.yml, src/render-images.py
=> Only use the manager version as default if the manager is not latest

environments/manager/images.yml, src/render-images.py
=> Use MANAGER_VERSION

inventory/51-kolla, requirements.txt, src/check-sorting-of-inventory-files.py
Part of osism/cfg-generics#272
=> Script added to check alphabetical sorting in inventory

inventory/50-kolla, inventory/51-kolla
=> inventory: remove monasca

inventory/60-generic
=> inventory: add osquery group

environments/manager/run.sh
=> manager: k8s playbook requires parameters from infrastructure env

inventory/50-kolla
Signed-off-by: Dr. Jens Harbott <harbott@osism.tech>
=> Fix openstack-dashboards group name in kolla inventory

inventory/50-kolla, inventory/51-kolla
=> kolla: add skyline groups

environments/manager/images.yml
=> manager: add postgres_upgrade image

requirements.txt
=> Remove ruaeml.yaml

.flake8, .zuul.yaml, releasenotes/notes/manager-version-from-config-repo-1323f3e0575c1a48.yaml, src/check-sorting-of-inventory-files.py, src/render-ansible-requirements.py, src/render-images.py
=> Get manager version from config repo when not set

.zuul.yaml
Related to c8430164ecf8f1782bbf4eb162980ae243121a47
=> zuul: overwrite the secret

.zuul.yaml
Related to 38bc0165f2465c9c60e86b3d10a10448c54e7aed
=> zuul: add missing pass-to-parent

inventory/50-infrastruture
=> Remove openldap group

.gitignore, .zuul.yaml, Makefile, requirements.txt, tox.ini
Related to osism/cfg-cookiecutter#570
=> Add Makefile to automate common tasks

environments/manager/run.sh
Add a mechanism which compares the name of the used branch in the source folder in the seed phase with the configured branch to prevent unexpected results.
=> Check configured branch

gilt.yml, src/set-docker-version.py
This sets the docker_version as it is defined in osism/release. According to the manager version.
=> Enable docker_version management

src/set-versions.py
=> Set ansible collection versions in environments/manager/run.sh

Makefile
Related to 7d86a8475f1bcd850e226ba86d5597585ea5a47e
=> Allow to still overwrite the used branch in the Makefile

environments/manager/run.sh
=> manager: detect if ANSIBLE_ASK_VAULT_PASS is required

src/set-versions.py
Related to 0efc74f3feaa9cbdb202426ebe37ec5edb2fcdcd
=> Also manage the docker_cli_version

src/set-versions.py
They are not visible when running the script with gilt.
=> Remove some print statements from src/set-versions.py

Makefile
https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
=> Use .PHONY in the Makefile

inventory/60-generic
=> inventory: remove kompose group

Makefile
Is a dependency for https://github.com/osism/osism.github.io/pull/610
=> improve secret management

Makefile
- Improve encryption and decryption when working on the manager
- Add targets for the encryption and the decryption of ceph secrets
This change is a precondition to https://github.com/osism/osism.github.io/pull/626
=> Improve encryption and decryption

inventory/50-monitoring
=> Remove openstack-health-monitor group

environments/manager/images.yml
=> manager: add pgautoupgrade image

inventory/50-infrastruture
=> inventory: remove tang group

inventory/50-infrastruture
=> inventory: remove clevis group

src/render-images.py
Related to bc602f270524826b7eb57263701208e64d7d802a
=> Overwrite the version, not the image
